### ISSUE TITLE
Compilation fails on Xcode10.1

### ISSUE THREAD

**Issue by thibauddavid** [BatchLabs/ios-sdk#15] opened 2018-10-31 15:09 UTC
Hi,

XCode10.1 (released today) breaks SDK compilation when building for device due to arm64e architecture not being found on framework.

```
fatal error: lipo: -extract arm64e specified but fat file:/Users/****/Library/Developer/Xcode/DerivedData/******/Frameworks/BatchExtension.framework/BatchExtension does not contain that architecture
fatal error: lipo: can't open input file: /Users/****/Library/Developer/Xcode/DerivedData/*****/Frameworks/BatchExtension.framework/BatchExtension-arm64e (No such file or directory)
rm: /Users/****/Library/Developer/Xcode/DerivedData/Frameworks/BatchExtension.framework/BatchExtension-arm64e: No such file or directory
/Users/****/Library/Developer/Xcode/DerivedData/Frameworks/BatchExtension.framework/BatchExtension: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

Still works as expected on simulator.

SDK added via Cocoapods, using run script to strip unused architectures when building `# Strip Batch framework
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/BatchExtension.framework/strip-frameworks.sh"`

Thanks

**Comment by abarisain** [comment] 2018-10-31 15:19
Hello,

We'll release the arm64e slices after some testing (there has been quite weird issues with the 10.1 betas).

A fix until now is to override the "Valid architectures" build setting with everything except arm64e. It should usually be "arm64 armv7 armv7s" for most projects

**Comment by thibauddavid** [comment] 2018-10-31 15:30
Thanks for answering this quick. Keep us in touch once fixed if you can :)

**Comment by abarisain** [comment] 2018-10-31 15:33
Sure! We'll have a patch release with arm64e slices by next tuesday

**Comment by ScreamZ** [comment] 2018-11-02 11:14
Also interested :), ping us :)

**Comment by abarisain** [comment] 2018-11-05 15:33
Batch 1.13.1 has been released. Both the main framework and BatchExtension now have a arm64e slice: you can now remove the workaround described higher up

**Comment by abarisain** [comment] 2018-11-06 16:29
Reopening: Looks like Xcode didn't generate Bitcode for arm64e, which leads to problems when archiving for ad-hoc distribution

**Comment by abarisain** [comment] 2018-11-07 09:49
While we figure out how to make Xcode produce arm64e bitcode, here is a strip-frameworks.sh that just ignores the arm64e slice. No changes to "valid architectures" needed.


You can also apply this to Batch 1.13.0 and lower, as this includes a fix to unexpected VALID_ARCHITECTURE values

```
#  strip-frameworks.sh
#  BatchExtension
#
#  Copyright © 2016 Batch.com. All rights reserved.

FRAMEWORK_DIRECTORY="${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/BatchExtension.framework"
FRAMEWORK_BINARY_PATH="${FRAMEWORK_DIRECTORY}/BatchExtension"

individual_slices_paths=()

# Split the fat framework into one file per valid slice

for arch in $VALID_ARCHS; do
    # Temporary arm64e patch, remove once 1.13.2 is released
    if [[ $arch == "arm64e" ]]; then
      continue
    fi

    slice_path="$FRAMEWORK_BINARY_PATH-$arch"
    lipo -extract "$arch" "$FRAMEWORK_BINARY_PATH" -o "$slice_path"
    if [ $? -eq 0 ]; then
      individual_slices+=("$slice_path")
    fi
done

# Delete the fat framework and merge everything back, then clean up
rm "${FRAMEWORK_BINARY_PATH}"
lipo -create "${individual_slices[@]}" -o "${FRAMEWORK_BINARY_PATH}"
rm "${individual_slices[@]}"

# Codesign if needed
if [ "${CODE_SIGNING_REQUIRED}" == "YES" ]; then
  /usr/bin/codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY}" --preserve-metadata=identifier,entitlements "${FRAMEWORK_BINARY_PATH}"
fi
```

**Comment by abarisain** [comment] 2018-11-07 15:35
Didn't find a way to make Xcode output arm64e bitcode yet 

Since the arm64e slices are removed when submitting on TestFlight/App Store anyway (https://developer.apple.com/documentation/xcode_release_notes/xcode_10_1_release_notes?language=objc) , the plan is to update the 1.13.1 release zips to include the patched shell script.
The frameworks will still have their arm64e slices, but the extension strip script will ignore it.

**Comment by ScreamZ** [comment] 2018-11-15 10:03
So can we consider this as fixed ?

**Comment by abarisain** [comment] 2018-11-15 10:06
It is fixed (more exactly: it has been worked around), but it might break when arm64e goes out of preview

**Comment by abarisain** [comment] 2019-02-18 15:13
Officially marking this as fixed. Will reopen when something breaks with an Xcode update

**Closed** 2019-02-18 15:13 UTC

**Comment by mboudaoud** [comment] 2019-02-26 10:29
Hello, still having with Xcode 10.1 and Batch 1.13.2, from what I have understood from this thread, this issue is supposed to be solved with Batch 1.13.2 ? Should I add the script ?

**Comment by abarisain** [comment] 2019-02-26 10:43
The issue is solved with 1.13.2 but you have to redownload the extension and replace the one in your project

**Comment by amaurydavid** [comment] 2019-03-27 13:00
I too am having this issue with Batch 1.13.2 using cocoapods when archiving. What do you mean by redownload the extension ?

**Comment by abarisain** [comment] 2019-03-27 14:08
It is needed to manually redownload BatchExtension from github or our website and upgrade it by copying it

The extension is not upgradable via cocoapods for the moment

**Comment by amaurydavid** [comment] 2019-03-27 14:51
Oh ok I missed the part where the extension framework had to be included manually. Now it works fine thanks =)
