### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by abiaad** [BatchLabs/ios-sdk#5] opened 2017-01-30 13:24 UTC
Do you provide any Carthage support ?
If no, is it planned ?

Thanks

**Comment by abarisain** [comment] 2017-01-30 13:28
Hello!

Yes, this is definitely on our roadmap.  
The problem is that we provide a static framework, which is unsupported by Carthage. 

Once we finish migrating to a dynamic framework, we'll be able to work on Carthage support.

**Comment by abiaad** [comment] 2017-01-30 13:29
Ok cool ! Can't wait ;)

**Comment by jasondibenedetto** [comment] 2017-05-15 01:49
Any update on this?

**Comment by abarisain** [comment] 2017-05-15 22:32
Hi!

Sorry, but we're still not a dynamic framework yet. There are a couple of roadblocks preventing us to do so: Xamarin compatibility, dyld speed, ...

**Comment by abiaad** [comment] 2017-10-13 11:43
Hello !

Any update ?

**Comment by abarisain** [comment] 2018-01-10 09:49
Hello,

Unfortunately, I don't have any timeframe for when we'll migrate to a dynamic framework, because of the complexity involved. 

I'll close this issue in the meantime, but Carthage will be supported as soon as it's possible.

**Closed by abarisain** 2018-01-10 09:49 UTC

**Comment by abarisain** [comment] 2018-01-30 15:25
Carthage seems to have been updated with static libraries support.

We internally reopened this issue, and will explore Carthage compatibility again :)
